/*Apaga os relacionamentos*/
ALTER TABLE LABDATABASE.DEPENDENTE DROP CONSTRAINT FUNCIONARIO_DEPENDENTE_FK;


/*Apaga as tabelas*/
DROP TABLE LABDATABASE.FUNCIONARIO;
DROP TABLE LABDATABASE.DEPENDENTE;


/*Apaga as sequences*/
DROP SEQUENCE LABDATABASE.DEPENDENTE_COD_DEP_SEQ;
DROP SEQUENCE LABDATABASE.FUNCIONARIO_MATRICULA_SEQ;

/*Cria as tabelas*/
CREATE TABLE LABDATABASE.FUNCIONARIO (
                MATRICULA NUMBER NOT NULL,
                CPF_FUNC VARCHAR2(14) NOT NULL,
                NOME_FUNC VARCHAR2(255) NOT NULL,
                CARGO VARCHAR2(255) NOT NULL,
                SEXO_FUNC VARCHAR(1) NOT NULL,
                CONSTRAINT FUNCIONARIO_PK PRIMARY KEY (MATRICULA)
);

CREATE TABLE LABDATABASE.DEPENDENTE (
                COD_DEP NUMBER NOT NULL,
                CPF_DEP VARCHAR2(11) NULL,
                NOME_DEP VARCHAR2(255) NOT NULL,
                SEXO_DEP VARCHAR(1) NOT NULL,
                CONSTRAINT DEPENDENTE_PK PRIMARY KEY (COD_DEP)
);


/*Cria as sequences*/
CREATE SEQUENCE LABDATABASE.DEPENDENTE_COD_DEP_SEQ;
CREATE SEQUENCE LABDATABASE.FUNCIONARIO_MATRICULA_SEQ;

/*Cria os relacionamentos*/
ALTER TABLE LABDATABASE.DEPENDENTE ADD CONSTRAINT FUNCIONARIO_DEPENDENTE_FK
FOREIGN KEY (MATRTICULA)
REFERENCES LABDATABASE.FUNCIONARIO (MATRICULA)
NOT DEFERRABLE;



/*Garante acesso total as tabelas*/
GRANT ALL ON LABDATABASE.FUNCIONARIO TO LABDATABASE;
GRANT ALL ON LABDATABASE.DEPENDENTE TO LABDATABASE;


ALTER USER LABDATABASE quota unlimited on USERS;
